"""
config_example.py
------------------

example config for testing
"""

## fully expanded example config
config_ex ={
    'Input_dir': './example_data',
    'Output_dir': 'test-out/',
    'Control_dir': './',
    'use_jit': 'no',
    'save_runtime_data': {
        'area': True,
        'ald': True,
        'climate_event': True,
        'drainage': True,
        'ice': True,
        'lake_pond': True,
        'poi': True
    },
    'log_each_time_step': True,
    'Results_onscreen': True,
    'save_log_to': False,
    'Archive_simulation': True,
    'Simulation_name': 'Historical_1901-2006',
    'Test_code': False,
    'Test_code_duration': 2,
    'skip_all_figures': False,
    'Archive_data': {
        'Simulation_Summary': True,
        'Initialization': True,
        'Met': True,
        'All_Cohorts': True,
        'Lakes': True,
        'Other_Cohorts': True,
        'Ponds': True,
        'Figures': True
    },
    'Initialize_Control': {
        'Initial_Cohort_Distribution_Figure': True,
        'Meadow_WT_Y_Figure': True,
        'Meadow_WT_M_Figure': True,
        'Meadow_WT_O_Figure': True,
        'LCP_WT_Y_Figure': True,
        'LCP_WT_M_Figure': True,
        'LCP_WT_O_Figure': True,
        'CLC_WT_Y_Figure': True,
        'CLC_WT_M_Figure': True,
        'CLC_WT_O_Figure': True,
        'FCP_WT_Y_Figure': True,
        'FCP_WT_M_Figure': True,
        'FCP_WT_O_Figure': True,
        'HCP_WT_Y_Figure': True,
        'HCP_WT_M_Figure': True,
        'HCP_WT_O_Figure': True,
        'Ponds_WT_Y_Figure': True,
        'Ponds_WT_M_Figure': True,
        'Ponds_WT_O_Figure': True,
        'LargeLakes_WT_Y_Figure': True,
        'LargeLakes_WT_M_Figure': True,
        'LargeLakes_WT_O_Figure': True,
        'MediumLakes_WT_Y_Figure': True,
        'MediumLakes_WT_M_Figure': True,
        'MediumLakes_WT_O_Figure': True,
        'SmallLakes_WT_Y_Figure': True,
        'SmallLakes_WT_M_Figure': True,
        'SmallLakes_WT_O_Figure': True,
        'CoastalWaters_WT_O_Figure': True,
        'DrainedSlope_WT_M_Figure': True,
        'DrainedSlope_WT_O_Figure': True,
        'DrainedSlope_WT_Y_Figure': True,
        'NoData_WT_O_Figure': True,
        'Rivers_WT_M_Figure': True,
        'Rivers_WT_O_Figure': True,
        'Rivers_WT_Y_Figure': True,
        'SandDunes_WT_M_Figure': True,
        'SandDunes_WT_O_Figure': True,
        'SandDunes_WT_Y_Figure': True,
        'SaturatedBarrens_WT_M_Figure': True,
        'SaturatedBarrens_WT_O_Figure': True,
        'SaturatedBarrens_WT_Y_Figure': True,
        'Shrubs_WT_O_Figure': True,
        'Urban_WT_O_Figure': True,
        'Normalized_Cohort_Distribution_Figure': True,
        'Meadow_WT_Y_Normal': True,
        'Meadow_WT_M_Normal': True,
        'Meadow_WT_O_Normal': True,
        'LCP_WT_Y_Normal': True,
        'LCP_WT_M_Normal': True,
        'LCP_WT_O_Normal': True,
        'CLC_WT_Y_Normal': True,
        'CLC_WT_M_Normal': True,
        'CLC_WT_O_Normal': True,
        'FCP_WT_Y_Normal': True,
        'FCP_WT_M_Normal': True,
        'FCP_WT_O_Normal': True,
        'HCP_WT_Y_Normal': True,
        'HCP_WT_M_Normal': True,
        'HCP_WT_O_Normal': True,
        'Ponds_WT_Y_Normal': True,
        'Ponds_WT_M_Normal': True,
        'Ponds_WT_O_Normal': True,
        'LargeLakes_WT_Y_Normal': True,
        'LargeLakes_WT_M_Normal': True,
        'LargeLakes_WT_O_Normal': True,
        'MediumLakes_WT_Y_Normal': True,
        'MediumLakes_WT_M_Normal': True,
        'MediumLakes_WT_O_Normal': True,
        'SmallLakes_WT_Y_Normal': True,
        'SmallLakes_WT_M_Normal': True,
        'SmallLakes_WT_O_Normal': True,
        'CoastalWaters_WT_O_Normal': True,
        'DrainedSlope_WT_M_Normal': True,
        'DrainedSlope_WT_O_Normal': True,
        'DrainedSlope_WT_Y_Normal': True,
        'NoData_WT_O_Normal': True,
        'Rivers_WT_M_Normal': True,
        'Rivers_WT_O_Normal': True,
        'Rivers_WT_Y_Normal': True,
        'SandDunes_WT_M_Normal': True,
        'SandDunes_WT_O_Normal': True,
        'SandDunes_WT_Y_Normal': True,
        'SaturatedBarrens_WT_M_Normal': True,
        'SaturatedBarrens_WT_O_Normal': True,
        'SaturatedBarrens_WT_Y_Normal': True,
        'Shrubs_WT_O_Normal': True,
        'Urban_WT_O_Normal': True,
        'Initial_Cohort_Age_Figure': True,
        'Meadow_WT_Y_Age': True,
        'Meadow_WT_M_Age': True,
        'Meadow_WT_O_Age': True,
        'LCP_WT_Y_Age': True,
        'LCP_WT_M_Age': True,
        'LCP_WT_O_Age': True,
        'CLC_WT_Y_Age': True,
        'CLC_WT_M_Age': True,
        'CLC_WT_O_Age': True,
        'FCP_WT_Y_Age': True,
        'FCP_WT_M_Age': True,
        'FCP_WT_O_Age': True,
        'HCP_WT_Y_Age': True,
        'HCP_WT_M_Age': True,
        'HCP_WT_O_Age': True,
        'Ponds_WT_Y_Age': True,
        'Ponds_WT_M_Age': True,
        'Ponds_WT_O_Age': True,
        'LargeLakes_WT_Y_Age': True,
        'LargeLakes_WT_M_Age': True,
        'LargeLakes_WT_O_Age': True,
        'MediumLakes_WT_Y_Age': True,
        'MediumLakes_WT_M_Age': True,
        'MediumLakes_WT_O_Age': True,
        'SmallLakes_WT_Y_Age': True,
        'SmallLakes_WT_M_Age': True,
        'SmallLakes_WT_O_Age': True,
        'CoastalWaters_WT_O_Age': True,
        'DrainedSlope_WT_M_Age': True,
        'DrainedSlope_WT_O_Age': True,
        'DrainedSlope_WT_Y_Age': True,
        'NoData_WT_O_Age': True,
        'Rivers_WT_M_Age': True,
        'Rivers_WT_O_Age': True,
        'Rivers_WT_Y_Age': True,
        'SandDunes_WT_M_Age': True,
        'SandDunes_WT_O_Age': True,
        'SandDunes_WT_Y_Age': True,
        'SaturatedBarrens_WT_M_Age': True,
        'SaturatedBarrens_WT_O_Age': True,
        'SaturatedBarrens_WT_Y_Age': True,
        'Shrubs_WT_O_Age': True,
        'Urban_WT_O_Age': True
    },
    'initialization_year': 1900,
    'start_year': 1901,
    'Target_resolution': [1000, 1000],
    'Initial_Area_data': [
        '../barrow_data/Meadow_WetlandTundra_Young.tif',
        '../barrow_data/Meadow_WetlandTundra_Medium.tif',
        '../barrow_data/Meadow_WetlandTundra_Old.tif',
        '../barrow_data/LowCenterPolygon_WetlandTundra_Young.tif',
        '../barrow_data/LowCenterPolygon_WetlandTundra_Medium.tif',
        '../barrow_data/LowCenterPolygon_WetlandTundra_Old.tif',
        '../barrow_data/CoalescentLowCenterPolygon_WetlandTundra_Young.tif',
        '../barrow_data/CoalescentLowCenterPolygon_WetlandTundra_Medium.tif',
        '../barrow_data/CoalescentLowCenterPolygon_WetlandTundra_Old.tif',
        '../barrow_data/FlatCenterPolygon_WetlandTundra_Young.tif',
        '../barrow_data/FlatCenterPolygon_WetlandTundra_Medium.tif',
        '../barrow_data/FlatCenterPolygon_WetlandTundra_Old.tif',
        '../barrow_data/HighCenterPolygon_WetlandTundra_Young.tif',
        '../barrow_data/HighCenterPolygon_WetlandTundra_Medium.tif',
        '../barrow_data/HighCenterPolygon_WetlandTundra_Old.tif',
        '../barrow_data/Ponds_WetlandTundra_Young.tif',
        '../barrow_data/Ponds_WetlandTundra_Medium.tif',
        '../barrow_data/Ponds_WetlandTundra_Old.tif',
        '../barrow_data/LargeLakes_WetlandTundra_Young.tif',
        '../barrow_data/LargeLakes_WetlandTundra_Medium.tif',
        '../barrow_data/LargeLakes_WetlandTundra_Old.tif',
        '../barrow_data/MediumLakes_WetlandTundra_Young.tif',
        '../barrow_data/MediumLakes_WetlandTundra_Medium.tif',
        '../barrow_data/MediumLakes_WetlandTundra_Old.tif',
        '../barrow_data/SmallLakes_WetlandTundra_Young.tif',
        '../barrow_data/SmallLakes_WetlandTundra_Medium.tif',
        '../barrow_data/SmallLakes_WetlandTundra_Old.tif',
        '../barrow_data/CoastalWaters_WetlandTundra_Old.tif',
        '../barrow_data/DrainedSlope_WetlandTundra_Medium.tif',
        '../barrow_data/DrainedSlope_WetlandTundra_Old.tif',
        '../barrow_data/DrainedSlope_WetlandTundra_Young.tif',
        '../barrow_data/NoData_WetlandTundra_Old.tif',
        '../barrow_data/Rivers_WetlandTundra_Medium.tif',
        '../barrow_data/Rivers_WetlandTundra_Old.tif',
        '../barrow_data/Rivers_WetlandTundra_Young.tif',
        '../barrow_data/SandDunes_WetlandTundra_Medium.tif',
        '../barrow_data/SandDunes_WetlandTundra_Old.tif',
        '../barrow_data/SandDunes_WetlandTundra_Young.tif',
        '../barrow_data/SaturatedBarrens_WetlandTundra_Medium.tif',
        '../barrow_data/SaturatedBarrens_WetlandTundra_Old.tif',
        '../barrow_data/SaturatedBarrens_WetlandTundra_Young.tif',
        '../barrow_data/Shrubs_WetlandTundra_Old.tif',
        '../barrow_data/Urban_WetlandTundra_Old.tif'
    ],
    'Met_Control': {
        'degree_day_method': 'read',
        'TDD_file': 'Degree_Days/barrow_tdd/barrow_tdd.yml',
        'FDD_file': 'Degree_Days/barrow_fdd/barrow_fdd.yml',
        'Degree_Day_Output': True,
        'TDD_Output': 'TDD_output',
        'FDD_Output': 'FDD_output',
        'climate_blocks': 'random',
        'climate_block_lower_bound': 5,
        'climate_block_upper_bound': 25,
        'climate_event_probability': 0.005,
        'lakes_drain_to': 'Meadow_WT_Y',
        'pond_drain_rate_<0.01': 0.0005,
        'pond_drain_rate_0.01<0.1': 0.0005,
        'pond_drain_rate_0.1<0.4': 0.0005,
        'pond_drain_rate_0.4<1.0': 0.0005,
        'lake_drain_rate_<0.01': 0.0005,
        'lake_drain_rate_0.01<0.1': 0.001,
        'lake_drain_rate_0.1<0.4': 0.0017,
        'lake_drain_rate_0.4<1.0': 0.0025
    },
    'Terrestrial_Control': {
        'Ice_Distribution_Figure': True,
        'Drainage_Efficiency_Distribution': 'random',
        'Drainage_Efficiency_Random_Value': 0.85,
        'Drainage_Efficiency_Figure': True,
        'ALD_Distribution': 'random',
        'Initial_ALD_range': [0.3, 0.3],
        'ALD_Distribution_Output': True,
        'ALD_Factor_Output': False,
        'Meadow_WT_Y_PLF': 1.0,
        'Meadow_WT_M_PLF': 1.0,
        'Meadow_WT_O_PLF': 1.0,
        'LCP_WT_Y_PLF': 1.0,
        'LCP_WT_M_PLF': 1.0,
        'LCP_WT_O_PLF': 1.0,
        'CLC_WT_Y_PLF': 1.0,
        'CLC_WT_M_PLF': 1.0,
        'CLC_WT_O_PLF': 1.0,
        'FCP_WT_Y_PLF': 1.0,
        'FCP_WT_M_PLF': 1.0,
        'FCP_WT_O_PLF': 1.0,
        'HCP_WT_Y_PLF': 1.0,
        'HCP_WT_M_PLF': 1.0,
        'HCP_WT_O_PLF': 1.0,
        'Ponds_WT_Y_PLF': 1.0,
        'Ponds_WT_M_PLF': 1.0,
        'Ponds_WT_O_PLF': 1.0,
        'LargeLakes_WT_Y_PLF': 1.0,
        'LargeLakes_WT_M_PLF': 1.0,
        'LargeLakes_WT_O_PLF': 1.0,
        'MediumLakes_WT_Y_PLF': 1.0,
        'MediumLakes_WT_M_PLF': 1.0,
        'MediumLakes_WT_O_PLF': 1.0,
        'SmallLakes_WT_Y_PLF': 1.0,
        'SmallLakes_WT_M_PLF': 1.0,
        'SmallLakes_WT_O_PLF': 1.0,
        'CoastalWaters_WT_O_PLF': 1.0,
        'DrainedSlope_WT_M_PLF': 1.0,
        'DrainedSlope_WT_O_PLF': 1.0,
        'DrainedSlope_WT_Y_PLF': 1.0,
        'NoData_WT_O_PLF': 1.0,
        'Rivers_WT_M_PLF': 1.0,
        'Rivers_WT_O_PLF': 1.0,
        'Rivers_WT_Y_PLF': 1.0,
        'SandDunes_WT_M_PLF': 1.0,
        'SandDunes_WT_O_PLF': 1.0,
        'SandDunes_WT_Y_PLF': 1.0,
        'SaturatedBarrens_WT_M_PLF': 1.0,
        'SaturatedBarrens_WT_O_PLF': 1.0,
        'SaturatedBarrens_WT_Y_PLF': 1.0,
        'Shrubs_WT_O_PLF': 1.0,
        'Urban_WT_O_PLF': 1.0,
        'Figure': True,
        'Movie': True
    },
    'Lake_Pond_Control': {
        'Lake_Distribution': 'Random',
        'Uniform_Lake_Depth': 3.5,
        'Lower_Lake_Depth': 2.2,
        'Upper_Lake_Depth': 5.0,
        'Pond_Distribution': 'Random',
        'Uniform_Pond_Depth': 1.5,
        'Lower_Pond_Depth': 1.25,
        'Upper_Pond_Depth': 1.7,
        'LargeLakes_WT_Y_Expansion': 0.0001,
        'LargeLakes_WT_M_Expansion': 0.0001,
        'LargeLakes_WT_O_Expansion': 0.0001,
        'MediumLakes_WT_Y_Expansion': 0.0001,
        'MediumLakes_WT_M_Expansion': 0.0001,
        'MediumLakes_WT_O_Expansion': 0.0001,
        'SmallLakes_WT_Y_Expansion': 0.0001,
        'SmallLakes_WT_M_Expansion': 0.0001,
        'SmallLakes_WT_O_Expansion': 0.0001,
        'Ponds_WT_Y_Expansion': 0.0001,
        'Ponds_WT_M_Expansion': 0.0001,
        'Ponds_WT_O_Expansion': 0.0001,
        'Ponds_fill_to': 'Meadow_WT_Y',
        'Ponds_WT_Y_Infill_Constant': 0.005,
        'Ponds_WT_M_Infill_Constant': 0.005,
        'Ponds_WT_O_Infill_Constant': 0.005,
        'Ponds_WT_Y_growth_time_required': 1,
        'Ponds_WT_M_growth_time_required': 1,
        'Ponds_WT_O_growth_time_required': 1,
        'ice_thickness_distribution': 'Random',
        'ice_thickness_uniform_alpha': 2.4,
        'Lower_ice_thickness_alpha': 2.2,
        'Upper_ice_thickness_alpha': 5.0,
        'LargeLakes_WT_Y_depth_control': 100,
        'LargeLakes_WT_M_depth_control': 100,
        'LargeLakes_WT_O_depth_control': 100,
        'MediumLakes_WT_Y_depth_control': 100,
        'MediumLakes_WT_M_depth_control': 100,
        'MediumLakes_WT_O_depth_control': 100,
        'SmallLakes_WT_Y_depth_control': 100,
        'SmallLakes_WT_M_depth_control': 100,
        'SmallLakes_WT_O_depth_control': 100,
        'Ponds_WT_Y_depth_control': 10,
        'Ponds_WT_M_depth_control': 10,
        'Ponds_WT_O_depth_control': 10,
        'figures': {
            'LargeLakes_WT_Y_Depth_Figure': True,
        'LargeLakes_WT_M_Depth_Figure': True,
        'LargeLakes_WT_O_Depth_Figure': True,
        'MediumLakes_WT_Y_Depth_Figure': True,
        'MediumLakes_WT_M_Depth_Figure': True,
        'MediumLakes_WT_O_Depth_Figure': True,
        'SmallLakes_WT_Y_Depth_Figure': True,
        'SmallLakes_WT_M_Depth_Figure': True,
        'SmallLakes_WT_O_Depth_Figure': True,
        'Ponds_WT_Y_Depth_Figure': True,
        'Ponds_WT_M_Depth_Figure': True,
        'Ponds_WT_O_Depth_Figure': True
        }
    },
    'Transition_order': [
        'Meadow_WT_Y',
        'Meadow_WT_M',
        'Meadow_WT_O',
        'LCP_WT_Y',
        'LCP_WT_M',
        'LCP_WT_O',
        'CLC_WT_Y',
        'CLC_WT_M',
        'CLC_WT_O',
        'FCP_WT_Y',
        'FCP_WT_M',
        'FCP_WT_O',
        'HCP_WT_Y',
        'HCP_WT_M',
        'HCP_WT_O',
        'Ponds_WT_Y',
        'Ponds_WT_M',
        'Ponds_WT_O',
        'LargeLakes_WT_Y',
        'LargeLakes_WT_M',
        'LargeLakes_WT_O',
        'MediumLakes_WT_Y',
        'MediumLakes_WT_M',
        'MediumLakes_WT_O',
        'SmallLakes_WT_Y',
        'SmallLakes_WT_M',
        'SmallLakes_WT_O'
    ],
    'cohorts': {
        'CLC_WT_O_Control': {
            'Transition_check_type': 'POI',
            'POI_Function': 'Sigmoid2',
            'transitions_to': 'FCP_WT_O',
            'Parameters': {
                'above': {
                    'sigmoid_A1': -0.1186,
                    'sigmoid_A2': 1.01,
                    'sigmoid_x0': 0.4856,
                    'sigmoid_dx': 0.1398,
                    'sigmoid2_K': 10.0,
                    'sigmoid2_C': 10.0,
                    'sigmoid2_A': 0.5,
                    'sigmoid2_B': -2.0,
                    'linear_a': 0.0,
                    'linear_b': 0.4,
                    'hill_B': 1.0,
                    'hill_N': 0.5
                },
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'CLC_WT_M_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'FCP_WT_M',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'MediumLakes_WT_O_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_O',
    'Figures': True,
    'Movie': False},
    'MediumLakes_WT_M_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_M',
    'Figures': True,
    'Movie': False},
    'CLC_WT_Y_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'FCP_WT_Y',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'MediumLakes_WT_Y_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_Y',
    'Figures': True,
    'Movie': False},
    'LargeLakes_WT_M_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_M',
    'Figures': True,
    'Movie': False},
    'LargeLakes_WT_O_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_O',
    'Figures': True,
    'Movie': False},
    'Meadow_WT_Y_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'LCP_WT_Y',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'LargeLakes_WT_Y_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_Y',
    'Figures': True,
    'Movie': False},
    'Meadow_WT_M_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'LCP_WT_M',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'Meadow_WT_O_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'LCP_WT_O',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'LCP_WT_Y_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'CLC_WT_Y',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'Ponds_WT_M_Control': {'Transition_check_type': 'pond_to_lake',
    'transitions_to': 'SmallLakes_WT_M',
    'Figures': True,
    'Movie': True},
    'HCP_WT_Y_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'Ponds_WT_Y',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'Ponds_WT_O_Control': {'Transition_check_type': 'pond_to_lake',
    'transitions_to': 'SmallLakes_WT_O',
    'Figures': True,
    'Movie': True},
    'SmallLakes_WT_M_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_M',
    'Figures': True,
    'Movie': False},
    'SmallLakes_WT_O_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_O',
    'Figures': True,
    'Movie': False},
    'LCP_WT_M_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'CLC_WT_M',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'LCP_WT_O_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'CLC_WT_O',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'SmallLakes_WT_Y_Control': {'Transition_check_type': 'lake_to_pond',
    'transitions_to': 'Ponds_WT_Y',
    'Figures': True,
    'Movie': False},
    'Ponds_WT_Y_Control': {'Transition_check_type': 'pond_to_lake',
    'transitions_to': 'SmallLakes_WT_Y',
    'Figures': True,
    'Movie': True},
    'HCP_WT_M_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'Ponds_WT_M',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'HCP_WT_O_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'Ponds_WT_O',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'FCP_WT_Y_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'HCP_WT_Y',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'FCP_WT_O_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'HCP_WT_O',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False},
    'FCP_WT_M_Control': {'Transition_check_type': 'POI',
    'POI_Function': 'Sigmoid2',
    'transitions_to': 'HCP_WT_M',
    'Parameters': {'above': {'sigmoid_A1': -0.1186,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 0.4856,
        'sigmoid_dx': 0.1398,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 0.5,
        'sigmoid2_B': -2.0,
        'linear_a': 0.0,
        'linear_b': 0.4,
        'hill_B': 1.0,
        'hill_N': 0.5},
        'below': {'sigmoid_A1': 0.03454,
        'sigmoid_A2': 1.01,
        'sigmoid_x0': 1.04,
        'sigmoid_dx': 0.1617,
        'sigmoid2_K': 10.0,
        'sigmoid2_C': 10.0,
        'sigmoid2_A': 3.0,
        'sigmoid2_B': -3.0,
        'linear_a': 0.0,
        'linear_b': 0.2,
        'hill_B': 1.0,
        'hill_N': 0.5}},
    'max_terrain_transition': 0.25,
    'ice_slope_poor': 0.05,
    'ice_slope_pore': 0.5,
    'ice_slope_wedge': 0.5,
    'ice_slope_massive': 1.0,
    'porosity': 0.5,
    'Figures': False,
    'Movie': False}},
    'model length': 108,
    'start year': 1901
}
